# Glossary candidate terms: (id, category, [names]) — names are the forms people type.
TERMS = [
    # --- advanced / analytics stats ---
    ("xg", "stat-advanced", ["xg", "expected goals", "xgf", "xga", "xgf percentage", "expected goals for", "expected goals against"]),
    ("ixg", "stat-advanced", ["ixg", "individual expected goals"]),
    ("gax", "stat-advanced", ["goals above expected", "gax"]),
    ("gsax", "stat-advanced", ["gsax", "goals saved above expected"]),
    ("gsaa", "stat-advanced", ["gsaa", "goals saved above average"]),
    ("corsi", "stat-advanced", ["corsi", "corsi for percentage", "cf percentage", "relative corsi"]),
    ("fenwick", "stat-advanced", ["fenwick"]),
    ("pdo", "stat-advanced", ["pdo"]),
    ("war", "stat-advanced", ["wins above replacement", "goals above replacement", "gar"]),
    ("hdcf", "stat-advanced", ["high danger chances", "high danger scoring chances", "hdcf"]),
    ("scf", "stat-advanced", ["scoring chances", "scoring chance"]),
    ("zone-starts", "stat-advanced", ["zone starts", "offensive zone starts", "zone start percentage"]),
    ("qoc", "stat-advanced", ["quality of competition", "quality of teammates"]),
    ("rapm", "stat-advanced", ["rapm"]),
    ("per60", "stat-advanced", ["points per 60", "per 60"]),
    ("zone-entries", "stat-advanced", ["zone entries", "controlled zone entries", "zone exits"]),
    ("shot-share", "stat-advanced", ["shot share", "shot attempts", "unblocked shot attempts"]),
    ("game-score", "stat-advanced", ["game score"]),
    ("primary-points", "stat-advanced", ["primary assists", "primary points"]),
    ("shot-quality", "stat-advanced", ["shot quality"]),
    ("score-adjusted", "stat-advanced", ["score adjusted"]),
    ("5v5", "stat-advanced", ["5v5", "five on five"]),
    ("even-strength", "stat-advanced", ["even strength"]),
    ("hd-sv", "stat-advanced", ["high danger save percentage"]),
    # --- traditional stats ---
    ("plus-minus", "stat-basic", ["plus minus"]),
    ("toi", "stat-basic", ["toi", "time on ice"]),
    ("sv-pct", "stat-basic", ["save percentage", "sv"]),
    ("gaa", "stat-basic", ["gaa", "goals against average"]),
    ("sh-pct", "stat-basic", ["shooting percentage"]),
    ("pim", "stat-basic", ["pim", "penalty minutes"]),
    ("fo-pct", "stat-basic", ["faceoff percentage", "faceoff win percentage"]),
    ("ppg", "stat-basic", ["ppg", "power play goal", "points per game"]),
    ("shg", "stat-basic", ["shg", "shorthanded goal", "short handed goal"]),
    ("gwg", "stat-basic", ["gwg", "game winning goal"]),
    ("otl", "stat-basic", ["otl", "overtime loss"]),
    ("pts-pct", "stat-basic", ["points percentage"]),
    ("row", "stat-basic", ["row", "regulation wins"]),
    ("hits-blocks", "stat-basic", ["takeaways", "giveaways", "blocked shots"]),
    ("shutout", "stat-basic", ["shutout"]),
    ("assist", "stat-basic", ["assist", "secondary assist"]),
    # --- rules / game terms ---
    ("icing", "rules", ["icing"]),
    ("offside", "rules", ["offside", "offsides"]),
    ("hat-trick", "rules", ["hat trick", "gordie howe hat trick"]),
    ("power-play", "rules", ["power play", "penalty kill"]),
    ("empty-net", "rules", ["empty net", "pulling the goalie"]),
    ("goalie-interference", "rules", ["goalie interference"]),
    ("too-many-men", "rules", ["too many men"]),
    ("delay-of-game", "rules", ["delay of game"]),
    ("high-sticking", "rules", ["high sticking"]),
    ("cross-checking", "rules", ["cross checking"]),
    ("slashing", "rules", ["slashing"]),
    ("hooking", "rules", ["hooking"]),
    ("tripping", "rules", ["tripping"]),
    ("boarding", "rules", ["boarding"]),
    ("charging", "rules", ["charging"]),
    ("roughing", "rules", ["roughing"]),
    ("interference", "rules", ["interference"]),
    ("holding", "rules", ["holding"]),
    ("embellishment", "rules", ["embellishment"]),
    ("major-penalty", "rules", ["major penalty", "minor penalty", "double minor"]),
    ("misconduct", "rules", ["misconduct", "game misconduct", "match penalty"]),
    ("penalty-shot", "rules", ["penalty shot"]),
    ("shootout", "rules", ["shootout"]),
    ("delayed-penalty", "rules", ["delayed penalty"]),
    ("hand-pass", "rules", ["hand pass"]),
    ("coaches-challenge", "rules", ["coaches challenge"]),
    ("crease", "rules", ["crease"]),
    ("blue-line", "rules", ["blue line", "red line"]),
    ("neutral-zone", "rules", ["neutral zone", "offensive zone", "defensive zone"]),
    ("slot", "rules", ["slot", "high slot"]),
    ("faceoff", "rules", ["faceoff"]),
    ("overtime", "rules", ["3 on 3 overtime"]),
    # --- play / tactics ---
    ("forecheck", "tactics", ["forecheck", "backcheck"]),
    ("cycle", "tactics", ["cycle"]),
    ("dump-and-chase", "tactics", ["dump and chase"]),
    ("trap", "tactics", ["neutral zone trap"]),
    ("breakout", "tactics", ["breakout"]),
    ("one-timer", "tactics", ["one timer"]),
    ("slap-shot", "tactics", ["slap shot", "wrist shot", "snap shot", "backhand"]),
    ("deke", "tactics", ["deke"]),
    ("five-hole", "tactics", ["five hole"]),
    ("top-shelf", "tactics", ["top shelf", "bar down"]),
    ("screen", "tactics", ["screen", "tip in"]),
    ("rebound", "tactics", ["rebound"]),
    ("line-change", "tactics", ["line change", "line combinations"]),
    # --- roles / roster ---
    ("enforcer", "roles", ["enforcer", "goon"]),
    ("grinder", "roles", ["grinder", "plumber"]),
    ("sniper", "roles", ["sniper", "playmaker"]),
    ("power-forward", "roles", ["power forward"]),
    ("two-way", "roles", ["two way forward", "two way player"]),
    ("stay-at-home", "roles", ["stay at home defenseman", "offensive defenseman"]),
    ("top-six", "roles", ["top six", "bottom six", "top four", "third pair"]),
    ("checking-line", "roles", ["checking line", "fourth line"]),
    ("centre", "roles", ["center", "winger", "left wing", "right wing", "defenseman"]),
    # --- contracts / cap ---
    ("ltir", "contracts", ["ltir", "long term injured reserve"]),
    ("elc", "contracts", ["elc", "entry level contract"]),
    ("rfa", "contracts", ["rfa", "restricted free agent"]),
    ("ufa", "contracts", ["ufa", "unrestricted free agent"]),
    ("offer-sheet", "contracts", ["offer sheet"]),
    ("buyout", "contracts", ["buyout"]),
    ("salary-cap", "contracts", ["salary cap", "cap hit", "aav"]),
    ("ntc", "contracts", ["no trade clause", "no movement clause", "nmc", "ntc"]),
    ("waivers", "contracts", ["waivers", "waiver wire"]),
    ("retention", "contracts", ["salary retention", "retained salary"]),
    ("arbitration", "contracts", ["salary arbitration", "arbitration"]),
    ("qualifying-offer", "contracts", ["qualifying offer"]),
    ("bridge-deal", "contracts", ["bridge deal"]),
    ("two-way-contract", "contracts", ["two way contract"]),
    ("conditional-pick", "contracts", ["conditional pick"]),
    ("ebug", "contracts", ["ebug", "emergency backup goalie"]),
    ("trade-deadline", "contracts", ["trade deadline"]),
    ("draft-lottery", "contracts", ["draft lottery"]),
    ("tanking", "contracts", ["tanking"]),
    # --- slang ---
    ("apple", "slang", ["apple", "biscuit", "dangle", "snipe", "celly", "chirp", "barn", "flow", "lettuce", "beauty", "wheel", "gino", "tilly", "bender", "sauce", "duster", "grocery stick", "pigeon", "cheese", "top cheese", "sin bin", "hospital pass", "cherry picking", "gongshow", "muffin", "plug", "tendy", "d man", "wheels", "bucket"]),
]

HUB = [
    "hockey terms", "hockey terminology", "hockey glossary", "hockey slang", "hockey lingo",
    "hockey stats explained", "nhl stats explained", "advanced hockey stats", "hockey advanced stats",
    "nhl advanced stats", "hockey analytics", "nhl analytics", "advanced stats hockey explained",
    "hockey stat abbreviations", "nhl stat abbreviations", "hockey abbreviations", "nhl abbreviations",
    "hockey penalties", "nhl penalties", "hockey rules", "nhl rules", "hockey penalties list",
    "hockey positions", "nhl salary cap terms", "nhl contract terms", "hockey slang terms",
    "what does gp mean in hockey", "what does a mean in hockey", "what does p mean in hockey",
    "what does ot mean in hockey", "what does so mean in hockey", "what does sog mean in hockey",
    "sog hockey", "what does ppp mean in hockey", "ppp hockey", "what does shp mean in hockey",
    "what does evg mean in hockey", "what does fow mean in hockey", "what does bks mean in hockey",
    "what does hit mean in hockey", "what does ga mean in hockey", "what does sa mean in hockey",
    "what does sv mean in hockey", "what does w mean in hockey", "what does l mean in hockey",
    "nhl standings abbreviations", "what does ow mean in hockey", "what does rw mean in hockey",
    "what does dfo mean in hockey", "dfo hockey", "what does a mean on a hockey jersey",
    "what does c mean on a hockey jersey", "moneypuck", "natural stat trick", "evolving hockey",
    "hockey reference", "nhl edge", "nhl edge stats", "hockey viz", "hockeyviz",
    "expected goals model", "how is xg calculated", "how is xg calculated hockey",
    "how are expected goals calculated", "how is corsi calculated", "how to calculate corsi",
    "how is pdo calculated", "how is gsax calculated", "how is save percentage calculated",
    "how is gaa calculated", "how to calculate gaa", "how to calculate save percentage",
    "how is plus minus calculated", "how is plus minus calculated in hockey",
    "xg vs actual goals", "corsi vs fenwick", "fenwick vs corsi", "xg vs corsi",
    "nhl xg leaders", "xg leaders nhl", "nhl expected goals leaders", "gsax leaders",
    "nhl gsax leaders", "nhl corsi leaders", "red wings advanced stats", "red wings stats",
    "red wings corsi", "red wings xg", "red wings expected goals",
]

TEMPLATES = [
    "{n}", "what is {n}", "what is {n} in hockey", "what is {n} in nhl", "{n} hockey", "{n} nhl",
    "nhl {n}", "hockey {n}", "what does {n} mean in hockey", "{n} meaning hockey",
    "{n} in hockey", "{n} hockey meaning", "{n} stat", "{n} hockey stat", "what is {n} hockey",
    "{n} definition hockey", "hockey {n} definition",
]
